export const UPDATE_LOADING = 'UPDATE_LOADING'
export const UPDATE_USER_INFO = 'UPDATE_USER_INFO'
export const UPDATE_LOGIN_STATUS = 'UPDATE_LOGIN_STATUS'
export const UPDATE_GUEST_STATUS = 'UPDATE_LOGIN_STATUS'
export const UPDATE_BET = 'UPDATE_BET'
export const DELETE_BET = 'DELETE_BET'
export const SET_APP_PARAMS = 'SET_APP_PARAMS'
export const UPDATE_COLLECT_FOOTBALL = 'UPDATE_COLLECT_FOOTBALL'
export const UPDATE_HOME_GAMES = 'UPDATE_HOME_GAMES'
export const UPDATE_PROJECT_CONFIG = 'UPDATE_PROJECT_CONFIG'
export const UPDATE_USERINFO_STATUS = 'UPDATE_USERINFO_STATUS'




